import { Camera, Vector3 } from 'three';
import type { World } from '../world/World';
export class Player {
  readonly position=new Vector3(0,25,0); velocity=new Vector3(); yaw=0; pitch=0; onGround=false; private keys=new Set<string>();
  constructor(readonly camera:Camera, private readonly world:World, private readonly canvas:HTMLElement){camera.position.copy(this.position);window.addEventListener('keydown',e=>this.keys.add(e.code));window.addEventListener('keyup',e=>this.keys.delete(e.code));canvas.addEventListener('click',()=>canvas.requestPointerLock());document.addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas){this.yaw-=e.movementX*.0024;this.pitch=Math.max(-1.48,Math.min(1.48,this.pitch-e.movementY*.0024));}});}
  update(dt:number){const forward=new Vector3(-Math.sin(this.yaw),0,-Math.cos(this.yaw)),right=new Vector3(forward.z,0,-forward.x),move=new Vector3();if(this.keys.has('KeyW'))move.add(forward);if(this.keys.has('KeyS'))move.sub(forward);if(this.keys.has('KeyD'))move.add(right);if(this.keys.has('KeyA'))move.sub(right);const speed=this.keys.has('ShiftLeft')?7.1:4.5;if(move.lengthSq())move.normalize().multiplyScalar(speed);this.velocity.x=move.x;this.velocity.z=move.z;if(this.keys.has('Space')&&this.onGround){this.velocity.y=8;this.onGround=false;}this.velocity.y-=22*dt;this.moveAxis('x',this.velocity.x*dt);this.moveAxis('z',this.velocity.z*dt);this.onGround=false;this.moveAxis('y',this.velocity.y*dt);this.camera.position.copy(this.position);this.camera.rotation.set(this.pitch,this.yaw,0,'YXZ');this.world.generateAround(this.position.x,this.position.z);}
  private moveAxis(axis:'x'|'y'|'z',amount:number){const next=this.position.clone();next[axis]+=amount;const half=.32, feet=next.y-1.62, head=next.y+.15;let hit=false;for(const x of [next.x-half,next.x+half])for(const z of [next.z-half,next.z+half])for(const y of [feet,feet+.8,head])if(this.world.solidAt(x,y,z))hit=true;if(hit){if(axis==='y'&&amount<0)this.onGround=true;this.velocity[axis]=0;}else this.position.copy(next);}
  blockIntersects(x:number,y:number,z:number){return this.position.x+.32>x&&this.position.x-.32<x+1&&this.position.z+.32>z&&this.position.z-.32<z+1&&this.position.y+.15>y&&this.position.y-1.62<y+1;}
}
