import './styles.css';
import { AmbientLight, BoxGeometry, Clock, Color, DirectionalLight, LineBasicMaterial, LineSegments, PerspectiveCamera, Scene, WebGLRenderer, EdgesGeometry, Mesh, MeshBasicMaterial, Raycaster, Vector2, Vector3, Group, Fog } from 'three';
import { block, BlockId } from './blocks/BlockRegistry'; import { Glowhorn } from './entities/Glowhorn';import { Inventory } from './inventory/Inventory';import { Player } from './player/Player';import { Hud } from './ui/Hud';import { loadGame, saveGame } from './save/SaveSystem';import { World } from './world/World';import { RECIPES } from './crafting/Recipes';
const isBlockId = (value: unknown): value is BlockId => typeof value === 'number' && Number.isInteger(value) && value >= 0 && value <= 12;
const hud=new Hud(); hud.onStart(start); function start(continuing:boolean){hud.show();const saved=continuing?loadGame():undefined;const seed=saved?.seed??Math.floor(Math.random()*999999);const canvas=document.querySelector<HTMLCanvasElement>('#game')!;const renderer=new WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;const scene=new Scene();scene.background=new Color('#86c9dc');scene.fog=new Fog('#86c9dc',35,110);const camera=new PerspectiveCamera(70,innerWidth/innerHeight,.1,150);const sun=new DirectionalLight('#fff0c5',2.4);sun.position.set(35,55,20);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);scene.add(sun,new AmbientLight('#8db6d0',1.35));const world=new World(scene,seed);if(saved)world.changes=new Map(saved.changes as [string,BlockId][]);world.generateAround(saved?.position[0]??0,saved?.position[2]??0);const player=new Player(camera,world,canvas);if(saved){player.position.fromArray(saved.position);}
 const inv=new Inventory();if(saved){inv.selected=saved.selected;for(let i=0;i<9;i++)inv.slots[i]=saved.slots[i]??null;}const outline=new LineSegments(new EdgesGeometry(new BoxGeometry(1.006,1.006,1.006)),new LineBasicMaterial({color:'#fff0af'}));outline.visible=false;scene.add(outline);const creatures=[new Glowhorn(world,8,8),new Glowhorn(world,-12,5),new Glowhorn(world,17,-9)];const ray=new Raycaster();ray.far=6;let target:{x:number;y:number;z:number;normal:Vector3;id:BlockId}|undefined;const particles=new Group();scene.add(particles);let worldTime=saved?.time??.25,frames=0,elapsed=0,lastSave=0;const clock=new Clock();
 function targetBlock(){ray.setFromCamera(new Vector2(),camera);const hit=ray.intersectObjects(world.group.children,true)[0];if(!hit||!hit.face){target=undefined;outline.visible=false;return;}const p=hit.point.clone().addScaledVector(hit.face.normal,-.01).floor();const id=world.getBlock(p.x,p.y,p.z);if(!id){target=undefined;return;}target={x:p.x,y:p.y,z:p.z,normal:hit.face.normal.clone(),id};outline.position.set(p.x+.5,p.y+.5,p.z+.5);outline.visible=true;}
 function burst(pos:Vector3,color:Color){for(let i=0;i<8;i++){const m=new Mesh(new BoxGeometry(.075,.075,.075),new MeshBasicMaterial({color}));m.position.copy(pos);m.userData.v=new Vector3((Math.random()-.5)*2,Math.random()*1.8,(Math.random()-.5)*2);m.userData.life=.45+Math.random()*.2;particles.add(m);}}
 window.addEventListener('contextmenu',e=>e.preventDefault());window.addEventListener('mousedown',e=>{if(document.pointerLockElement!==canvas||!target)return;if(e.button===0){world.setBlock(target.x,target.y,target.z,0);inv.add(target.id);burst(outline.position,block(target.id).color);hud.message(`Collected ${block(target.id).name}`);}if(e.button===2){const p=new Vector3(target.x,target.y,target.z).add(target.normal);const item=inv.selectedStack();if(item&&!player.blockIntersects(p.x,p.y,p.z)&&world.getBlock(p.x,p.y,p.z)===0){world.setBlock(p.x,p.y,p.z,item.id);inv.consumeSelected();hud.message(`Placed ${block(item.id).name}`);}}});window.addEventListener('keydown',e=>{if(e.code.startsWith('Digit')){const n=Number(e.code.slice(-1));if(n>=1&&n<=9)inv.selected=n-1;}});window.addEventListener('wheel',e=>{inv.selected=(inv.selected+(e.deltaY>0?1:8))%9;},{passive:true});addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});renderer.setSize(innerWidth,innerHeight);
 function tick(){const dt=Math.min(clock.getDelta(),.05);worldTime=(worldTime+dt/150)%1;const angle=worldTime*Math.PI*2;sun.position.set(Math.cos(angle)*55,Math.sin(angle)*60,25);sun.intensity=Math.max(.18,Math.sin(angle)*2.3+.25);scene.background=new Color().setHSL(.57,.47,Math.max(.09,.38+Math.sin(angle)*.2));player.update(dt);targetBlock();creatures.forEach(c=>c.update(dt,player));for(const p of [...particles.children]){const v=p.userData.v as Vector3;p.position.addScaledVector(v,dt);v.y-=6*dt;p.userData.life-=dt;if(p.userData.life<=0)particles.remove(p);}elapsed+=dt;frames++;if(elapsed>.5){hud.render(inv,frames/elapsed,seed,world.chunks.size);frames=elapsed=0;}if(performance.now()-lastSave>8000){saveGame({version:1,seed,position:player.position.toArray() as [number,number,number],time:worldTime,selected:inv.selected,slots:inv.slots,changes:[...world.changes]});lastSave=performance.now();}renderer.render(scene,camera);requestAnimationFrame(tick);}tick();}
